### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.metrics._dist_metrics'

### ISSUE THREAD

**Issue by JUNJIE99** [tsunghan-mama/RandLA-Net-pytorch#15]
@tsunghan-mama Hi! Thank you for your excellent work! I am trying to infer the sequence 08 by using the pre-trained model. However, an error occurred: ModuleNotFoundError: No module named 'sklearn.metrics._dist_metrics'.
I search the documents of pickle in [https://scikit-learn.org/stable/search.html?], and no version has  the module"sklearn.metrics._dist_metrics". Could you please provide some suggestions to solve this problem? 
Looking forward to your reply!
Thank you so much!

More Details about the error:
Traceback (most recent call last):
  File "test_SemanticKITTI.py", line 180, in <module>
    main()
  File "test_SemanticKITTI.py", line 176, in main
    tester.test()
  File "test_SemanticKITTI.py", line 99, in test
    self.rolling_predict()
  File "test_SemanticKITTI.py", line 110, in rolling_predict
    batch_data, input_inds, cloud_inds, min_possibility = next(iter_loader)
  File "/***/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/***/python3.7/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/***/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 34, in fetch
    data = next(self.dataset_iter)
  File "/***/RandLA-Net-pytorch-main/dataset/semkitti_testset.py", line 52, in spatially_regular_gen
    pc, tree, labels = self.get_data(pc_path)
  File "/***/RandLA-Net-pytorch-main/dataset/semkitti_testset.py", line 69, in get_data
    search_tree = pickle.load(f)
ModuleNotFoundError: No module named 'sklearn.metrics._dist_metrics'

**Comment by JUNJIE99** [comment]
I solved the problem! I made a mistake preparing the data.
